/**
 * @packageDocumentation
 * @module api.functional.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";
import TSON from "typescript-json";

import type { IUserUsecase } from "./../../../../src/api/user/application/port/user.usecase.port";

/**
 * 사용자 생성 API
 * 
 * @tag user
 * @returns 생성된 사용자 id
 * 
 * @controller UserController.create()
 * @path POST /users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function create
    (
        connection: IConnection
    ): Promise<create.Output>
{
    return Fetcher.fetch
    (
        connection,
        create.ENCRYPTED,
        create.METHOD,
        create.path()
    );
}
export namespace create
{
    export type Output = IUserUsecase.CreateResponse;

    export const METHOD = "POST" as const;
    export const PATH: string = "/users";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/users`;
    }
    export const stringify = (input: Input) => TSON.stringify(input);
}

/**
 * 사용자 기록 조회 API
 * 
 * @tag user
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param id 사용자 id
 * @returns 사용자 레이드 기록
 * 
 * @controller UserController.findOne()
 * @path GET /users/:user_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function findOne
    (
        connection: IConnection,
        id: number
    ): Promise<findOne.Output>
{
    return Fetcher.fetch
    (
        connection,
        findOne.ENCRYPTED,
        findOne.METHOD,
        findOne.path(id)
    );
}
export namespace findOne
{
    export type Output = IUserUsecase.FindOneResponse;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/:user_id";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(id: number): string
    {
        return `/users/${encodeURIComponent(id)}`;
    }
}